### ISSUE TITLE
infinite loop when start pos is on the lower part of the Maze

### ISSUE THREAD

**Issue by username-MIA** [kiethrios/reeborg-s-world-maze#1]
Hello kiethrios,

I found your solution while looking for other peoples attempts on solving the Maze challenge. 
After a few runs it ended with an infinite loop.
![image](https://user-images.githubusercontent.com/114924676/202154860-339fd982-c4ac-4a0a-8706-f09601dce004.png)

**Comment by username-MIA** [comment]
A possible solution for this issue is to change the order of the if conditions on the 

> def goal()

 while loop and adding a move step.
 So the def goal() function would look like this

`def goal():
    while not at_goal():
        if right_is_clear():    #changed line
            turn_right()        #changed line
            move()               #changed line
        elif front_is_clear():  #changed line
            move()               #changed line
        else:
            turn_left()`

When reeborg's start position is x = 3 and y = 4 you will still get an infinite loop 
![image](https://user-images.githubusercontent.com/114924676/202158555-7717fe00-7746-45a2-9a52-619d864e11af.png)

**Comment by username-MIA** [comment]
This is the solution I've come up with 
`def turn_right():
    turn_left()
    turn_left()
    turn_left()
    
	
def left_is_clear():
    turn_left()
    if front_is_clear():
        turn_left()
        turn_left()
        turn_left()
        return True
    else:
        turn_left()
        turn_left()
        turn_left()
        return False


while not at_goal():
    if right_is_clear() and front_is_clear() and left_is_clear():
        move()
    elif right_is_clear():
        turn_right()
        move()     
    elif not right_is_clear() and front_is_clear():
        move()
    elif not right_is_clear() and not front_is_clear():
        turn_left()
`

**Comment by kiethrios** [comment]
Thank you, I will come up with another one.

**Comment by kiethrios** [comment]
I fixed that. Please check and try again.
